# HarvestMoonMC Configuration

# Farm Region Settings
regions:
  # Regions will be saved here when created
  # Example format:
  # farm1:
  #   world: world
  #   min: {x: 10, y: 64, z: 10}
  #   max: {x: 20, y: 64, z: 20}

# Grinding System (Crop Quality)
grinding_system:
  # Quality tiers configuration
  quality_tiers:
    COMMON:
      display_name: "Common"
      name_suffix: "[Common]"
      lore: "Kualitas: Biasa"
      price_multiplier: 1.0
      weight: 70 # Chance weight (higher = more common)
      color: "WHITE"
    UNCOMMON:
      display_name: "Uncommon"
      name_suffix: "[Uncommon]"
      lore: "Kualitas: Tidak Biasa"
      price_multiplier: 1.5
      weight: 20
      color: "GREEN"
    RARE:
      display_name: "Rare"
      name_suffix: "[Rare]"
      lore: "Kualitas: Langka"
      price_multiplier: 2.5
      weight: 8
      color: "BLUE"
    EPIC:
      display_name: "Epic"
      name_suffix: "[Epic]"
      lore: "Kualitas: Epik"
      price_multiplier: 4.0
      weight: 2
      color: "DARK_PURPLE"
      
  # Base prices for crops
  base_prices:
    WHEAT: 5
    CARROT: 6
    POTATO: 6
    BEETROOT: 7
    
  # Tool modifiers (affects quality chance and price)
  hoe_modifiers:
    WOODEN_HOE: 1.0
    STONE_HOE: 1.2
    IRON_HOE: 1.5
    GOLDEN_HOE: 1.8
    DIAMOND_HOE: 2.0
    NETHERITE_HOE: 2.5
    
  # Enchantment modifiers
  enchantment_modifiers:
    FORTUNE:
      1: 1.1
      2: 1.2
      3: 1.3
    EFFICIENCY:
      1: 1.05
      2: 1.1
      3: 1.15
      4: 1.2
      5: 1.25

# Messages
messages:
  prefix: "&6[DragFarm] &r"
  wand_given: "Farm Region Selection Wand diberikan."
  pos1_selected: "Posisi 1 dipilih: %x%, %y%, %z%"
  pos2_selected: "Posisi 2 dipilih: %x%, %y%, %z%"
  region_created: "Region pertanian '%name%' berhasil dibuat!"
  region_exists: "Region dengan nama '%name%' sudah ada!"
  no_selection: "Pilih 2 posisi dengan wand terlebih dahulu!"
  no_permission: "Anda tidak memiliki izin untuk melakukan ini."
  xp_gained: "&a+%amount% Farming XP"
  level_up: "&aLevel up! Farming Skill naik ke level &6%level%&a!"
  wheat_only: "&cAnda hanya dapat memanen tanaman gandum di region pertanian."
  event_start: "&6&l✨ EVENT SPESIAL! &e&lJual tanaman dengan harga {multiplier}x lipat selama {duration} menit!"
  event_end: "&6&l✨ Event penjualan spesial telah berakhir!"
  harvest_limit_reset: "&aKuota panen Anda telah direset!"
  harvest_limit_reached: "&cAnda telah mencapai batas panen hari ini. Silakan tunggu reset."
  harvest_remaining: "&eSisa kuota panen hari ini: &6{count}"
  config_reloaded: "&aKonfigurasi plugin berhasil di-reload!"
  need_hoe: "&cYou must use a specific farming hoe to harvest here!" # Changed for clarity
  vanilla_hoe_in_farm_region: "&cYou can only use custom farming hoes in this region."
  custom_hoe_outside_farm_region: "&cHoe can only be used at /warp farm."
  zonk_harvest: "&c&lZONK! &r&cKamu tidak mendapatkan apa-apa dari panen ini."
  special_ability_activated: "&aSpecial ability &e'Divine Harvest'&a activated!"
  special_ability_cooldown: "&cAbility on cooldown! Time remaining: &e%time% seconds&c."
  special_ability_no_money: "&cNot enough money to use this ability. Cost: &e%cost%&c."
  special_ability_no_permission: "&cYou do not have permission to use this hoe's special ability."
  special_ability_not_available: "&cThis hoe does not have this special ability or it's currently disabled."
  special_ability_failed_region: "&cSpecial ability can only be used in farming regions." # This can be kept as a fallback

# Farming Settings
farming:
  animation_delay_ticks: 10
  enable_animations: true
  zonk_chance_percent: 5.0
  # Default Special Ability Settings (can be overridden per hoe in hoes.yml)
  default_special_ability:
    particle_type: "SMOKE_NORMAL" # Bukkit Particle enum name for grey particles
    sound_activate: "ENTITY_PLAYER_ATTACK_SWEEP"
    sound_impact: "BLOCK_GRASS_BREAK" # Sound when apple "lands" and harvests
    apple_fall_height: 3.0 # Blocks above player
    apple_fall_speed: -0.4 # Negative for downward

# Skills System
skills:
  # Base XP values for crops
  base_xp:
    WHEAT: 2
    CARROT: 3
    POTATO: 3
    BEETROOT: 4
    
  # Quality XP multipliers
  quality_xp_multiplier:
    COMMON: 1.0
    UNCOMMON: 1.5
    RARE: 2.0
    EPIC: 3.0
    
  # Player level impact
  quality_multiplier_per_level: 0.02  # 2% quality chance increase per level
  max_quality_multiplier: 2.0         # Maximum 100% bonus (2x base chance)

  # XP notification type: chat, actionbar, sound, none
  xp_notification: "actionbar"   # actionbar is less intrusive than chat
  total_xp_notification: false   # set to true to show accumulated XP instead of per-crop

# Pengaturan event penjualan spesial
events:
  min_interval_minutes: 40
  max_interval_minutes: 60
  min_duration_minutes: 5
  max_duration_minutes: 15
  possible_multipliers:
    - 2
    - 3
    - 4
  webhooks:
    enabled: true
    url: "https://discord.com/api/webhooks/1376932934711513159/2M7RVt7BaQ53zYHZQbfgqWJSugFi196qkMujUUxgDdUzIGhWdPsu8ZrexxtB9XdvW6z6"
    # Gunakan URL diatas sebagai default, atau ganti dengan URL webhook Anda sendiri

# Harvest settings
harvest:
  min_limit: 300
  max_limit: 500
  min_reset_time_minutes: 60
  max_reset_time_minutes: 180

# Hoe and GUI settings
customization:
  hoes:
    lore_format: # Adjusted for potentially infinite durability
      - "&7Harvest Multiplier: &a{multiplier}x"
      - "{durability_text}" # Placeholder for dynamic durability text
      - "{area_text}"
      - "{replant_text}"
      - "{special_ability_text}" # Placeholder for special ability lore
    area_text: "&7Area: &a{width}x{height}"
    replant_text: "&7Auto-replant: &aEnabled"
    no_replant_text: "&7Auto-replant: &cDisabled"
  gui:
    shop_title: "Toko Penjualan Hasil Panen" # Contoh judul untuk ShopGUI (jual crop)
    hoe_shop_main_title: "Toko Cangkul Kustom" # Judul baru untuk HoeShopGUI (beli cangkul)
    upgrade_title: "Tingkatkan Cangkul Anda" # Contoh judul untuk HoeShopGUI (upgrade)
    buy_button: "&a&lBeli ({price})" # Diperbarui agar lebih jelas
    upgrade_button: "&a&lUpgrade Sekarang"
    cancel_button: "&c&lBatal"
    confirmation_message: "&aBerhasil {action}!"

permissions:
  dragonfarm.hoe.specialability:
    description: Allows using the special ability of custom hoes.
    default: op