# HarvestMoonMC Configuration

# Farm Region Settings
regions:
  # Regions will be saved here when created
  # Example format:
  # farm1:
  #   world: world
  #   min: {x: 10, y: 64, z: 10}
  #   max: {x: 20, y: 64, z: 20}

# Grinding System (Crop Quality)
grinding_system:
  # Quality tiers configuration
  quality_tiers:
    COMMON:
      display_name: "Common"
      name_suffix: "[Common]"
      lore: "Kualitas: Biasa"
      price_multiplier: 1.0
      weight: 70 # Chance weight (higher = more common)
      color: "WHITE"
    UNCOMMON:
      display_name: "Uncommon"
      name_suffix: "[Uncommon]"
      lore: "Kualitas: Tidak Biasa"
      price_multiplier: 1.5
      weight: 20
      color: "GREEN"
    RARE:
      display_name: "Rare"
      name_suffix: "[Rare]"
      lore: "Kualitas: Langka"
      price_multiplier: 2.5
      weight: 8
      color: "BLUE"
    EPIC:
      display_name: "Epic"
      name_suffix: "[Epic]"
      lore: "Kualitas: Epik"
      price_multiplier: 4.0
      weight: 2
      color: "DARK_PURPLE"
      
  # Base prices for crops
  base_prices:
    WHEAT: 5
    CARROT: 6
    POTATO: 6
    BEETROOT: 7
    
  # Tool modifiers (affects quality chance and price)
  hoe_modifiers:
    WOODEN_HOE: 1.0
    STONE_HOE: 1.2
    IRON_HOE: 1.5
    GOLDEN_HOE: 1.8
    DIAMOND_HOE: 2.0
    NETHERITE_HOE: 2.5
    
  # Enchantment modifiers
  enchantment_modifiers:
    FORTUNE:
      1: 1.1
      2: 1.2
      3: 1.3
    EFFICIENCY:
      1: 1.05
      2: 1.1
      3: 1.15
      4: 1.2
      5: 1.25

# Messages
messages:
  prefix: "&6[HarvestMoonMC] &r"
  wand_given: "Farm Region Selection Wand diberikan."
  pos1_selected: "Posisi 1 dipilih: %x%, %y%, %z%"
  pos2_selected: "Posisi 2 dipilih: %x%, %y%, %z%"
  region_created: "Region pertanian '%name%' berhasil dibuat!"
  region_exists: "Region dengan nama '%name%' sudah ada!"
  no_selection: "Pilih 2 posisi dengan wand terlebih dahulu!"
  no_permission: "Anda tidak memiliki izin untuk melakukan ini."
  xp_gained: "&a+%amount% Farming XP"
  level_up: "&aLevel up! Farming Skill naik ke level &6%level%&a!"
  wheat_only: "&cAnda hanya dapat memanen tanaman gandum di region pertanian."
  event_start: "&6&l✨ EVENT SPESIAL! &e&lJual tanaman dengan harga {multiplier}x lipat selama {duration} menit!"
  event_end: "&6&l✨ Event penjualan spesial telah berakhir!"

# Farming Settings
farming:
  animation_delay_ticks: 10  # Delay between growth stages (in ticks, 20 ticks = 1 second)
  enable_animations: true    # Set to false to disable growth animations

# Skills System
skills:
  # Base XP values for crops
  base_xp:
    WHEAT: 2
    CARROT: 3
    POTATO: 3
    BEETROOT: 4
    
  # Quality XP multipliers
  quality_xp_multiplier:
    COMMON: 1.0
    UNCOMMON: 1.5
    RARE: 2.0
    EPIC: 3.0
    
  # Player level impact
  quality_multiplier_per_level: 0.02  # 2% quality chance increase per level
  max_quality_multiplier: 2.0         # Maximum 100% bonus (2x base chance)

  # XP notification type: chat, actionbar, sound, none
  xp_notification: "actionbar"   # actionbar is less intrusive than chat
  total_xp_notification: false   # set to true to show accumulated XP instead of per-crop

# Pengaturan event penjualan spesial
events:
  min_interval_minutes: 40
  max_interval_minutes: 60
  min_duration_minutes: 5
  max_duration_minutes: 15
  possible_multipliers:
    - 2
    - 3
    - 4