# HarvestMoonMC Configuration

# Farm Region Settings
regions:
  # Regions will be saved here when created
  # Example format:
  # farm1:
  #   world: world
  #   min: {x: 10, y: 64, z: 10}
  #   max: {x: 20, y: 64, z: 20}

# Grinding System (Crop Quality)
grinding_system:
  # Quality tiers configuration
  quality_tiers:
    COMMON:
      display_name: "Common"
      name_suffix: "[Common]"
      lore: "Kualitas: Biasa"
      price_multiplier: 1.0
      weight: 70 # Chance weight (higher = more common)
      color: "WHITE"
    UNCOMMON:
      display_name: "Uncommon"
      name_suffix: "[Uncommon]"
      lore: "Kualitas: Tidak Biasa"
      price_multiplier: 1.5
      weight: 20
      color: "GREEN"
    RARE:
      display_name: "Rare"
      name_suffix: "[Rare]"
      lore: "Kualitas: Langka"
      price_multiplier: 2.5
      weight: 8
      color: "BLUE"
    EPIC:
      display_name: "Epic"
      name_suffix: "[Epic]"
      lore: "Kualitas: Epik"
      price_multiplier: 4.0
      weight: 2
      color: "DARK_PURPLE"
      
  # Base prices for crops
  base_prices:
    WHEAT: 5
    CARROT: 6
    POTATO: 6
    BEETROOT: 7
    
  # Tool modifiers (affects quality chance and price)
  hoe_modifiers:
    WOODEN_HOE: 1.0
    STONE_HOE: 1.2
    IRON_HOE: 1.5
    GOLDEN_HOE: 1.8
    DIAMOND_HOE: 2.0
    NETHERITE_HOE: 2.5
    
  # Enchantment modifiers
  enchantment_modifiers:
    FORTUNE:
      1: 1.1
      2: 1.2
      3: 1.3
    EFFICIENCY:
      1: 1.05
      2: 1.1
      3: 1.15
      4: 1.2
      5: 1.25

# Messages
messages:
  prefix: "&6[HarvestMoonMC] &r"
  wand_given: "Farm Region Selection Wand diberikan."
  pos1_selected: "Posisi 1 dipilih: %x%, %y%, %z%"
  pos2_selected: "Posisi 2 dipilih: %x%, %y%, %z%"
  region_created: "Region pertanian '%name%' berhasil dibuat!"
  region_exists: "Region dengan nama '%name%' sudah ada!"
  no_selection: "Pilih 2 posisi dengan wand terlebih dahulu!"
  no_permission: "Anda tidak memiliki izin untuk melakukan ini."

# Farming Settings
farming:
  animation_delay_ticks: 10  # Delay between growth stages (in ticks, 20 ticks = 1 second)
  enable_animations: true    # Set to false to disable growth animations