name: DragonFarm
version: 1.0-SNAPSHOT
main: id.rnggagib.HarvestMoonMC
api-version: 1.20
authors: [rnggagib]
description: Custom farming plugin for Minecraft servers
softdepend: [Vault, WorldGuard, PlaceholderAPI]

commands:
  dragfarm:
    description: Main command for DragonFarm
    usage: /<command> [subcommand] [args]
    aliases: [df]
  hoeshop:
    description: Open the hoe shop
    usage: /<command>
    aliases: []
  farm:
    description: Warps you to the farm.
    usage: /farm
    aliases: [fm]

permissions:
  dragfarm.admin.wand:
    description: Allows use of the region selection wand
    default: op
  dragfarm.admin.create:
    description: Allows creation of farming regions
    default: op
  dragfarm.admin.list:
    description: Allows listing of farming regions
    default: op
  dragfarm.admin.info:
    description: Allows viewing region details
    default: op
  dragfarm.admin.delete:
    description: Allows deletion of farming regions
    default: op
  dragfarm.sell:
    description: Allows selling crops
    default: true
  dragfarm.shop:
    description: Allows access to the shop
    default: true
  dragfarm.stats:
    description: Allows checking farming skills
    default: true
  dragfarm.event:
    description: Allows checking current event status
    default: true
  dragfarm.admin.event:
    description: Allows managing sale events
    default: op
  dragfarm.admin.reload:
    description: Allows reloading the plugin configuration
    default: op
  dragfarm.admin.hoe:
    description: Allows managing custom hoes
    default: op
  dragfarm.hoe.upgrade:
    description: Allows upgrading farming hoes
    default: true