name: HarvestMoonMC
version: 1.0-SNAPSHOT
main: id.rnggagib.HarvestMoonMC
api-version: 1.20
authors: [rnggagib]
description: Harvest Moon-inspired farming plugin for Minecraft
softdepend: [Vault]

commands:
  hmc:
    description: Main command for HarvestMoonMC
    usage: /<command> [subcommand] [args]
    aliases: [harvestmoonmc]

permissions:
  harvestmoonmc.admin.wand:
    description: Allows use of the region selection wand
    default: op
  harvestmoonmc.admin.create:
    description: Allows creation of farming regions
    default: op
  harvestmoonmc.admin.list:
    description: Allows listing of farming regions
    default: op
  harvestmoonmc.admin.info:
    description: Allows viewing region details
    default: op
  harvestmoonmc.admin.delete:
    description: Allows deletion of farming regions
    default: op
  harvestmoonmc.sell:
    description: Allows selling crops
    default: true
  harvestmoonmc.shop:
    description: Allows access to the shop
    default: true